name: CI-CD Pipeline

on:
  push:
    branches:
      - avital-ben-simhon

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies (backend)
      run: |
        cd server
        npm install

    - name: Install dependencies (frontend)
      run: |
        cd react
        npm install

    - name: Build frontend
      run: |
        cd react
        npm run build

    - name: Deploy to server
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.EC2_HOST_AVITAL }}
        username: ${{ secrets.EC2_USER_AVITAL }}
        key: ${{ secrets.EC2_SSH_KEY_AVITAL }}
        script: |
          cd KonditoriaApp
          git pull
          docker compose down
          docker compose up -d --build
