name: Deploy to EC2
on:
  push:
    branches:
      - sarivolpo
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP_SARIVOLPO }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY_SARIVOLPO }}
          script: |
            cd /home/ubuntu/KonditoriaApp
            git fetch origin
            git checkout sarivolpo
            git pull origin sarivolpo
            
            cd react
            npm install
            npm run build
            
            # ניקוי הקבצים הישנים והעתקת החדשים
            sudo rm -rf /var/www/html/*
            sudo cp -r dist/* /var/www/html/
            
            sudo systemctl restart konditoria
