name: Deploy to EC2
on:
  push:
    branches:
      - sarivolpo
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP_SARIVOLPO }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY_SARIVOLPO }}
          script: |
            set -e  # גורם לכל שגיאה לעצור את התהליך מיד ולהפוך אותו ל"אדום"
            cd /home/ubuntu/KonditoriaApp
            git fetch origin
            git checkout sarivolpo
            git pull origin sarivolpo
            
            cd react
            npm install
            npm run build
            
            # בדיקה אם התיקייה קיימת
            if [ ! -d "dist" ]; then
              echo "Error: dist directory not found!"
              exit 1
            fi
            
            # העתקה (הנחה ששינית בעלות כפי שהסברתי בסעיף 1)
            rm -rf /var/www/html/*
            cp -r dist/* /var/www/html/
            
            sudo systemctl restart konditoria
