name: Deploy to EC2

on:
  push:
    branches:
      - Miri_Rosenbaum

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP_MIRI_ROSENBAUM }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY_MIRI_ROSENBAUM }}
          script: |
            # עדכון הקוד מהגיט בשרת
            cd /home/ubuntu/KonditoriaApp
            git checkout Miri_Rosenbaum
            git pull origin Miri_Rosenbaum

            # בנייה והעתקת הקליינט
            cd react
            npm install
            npm run build

            sudo cp -r dist/* /var/www/html/

            # אתחול הסרבר
            sudo systemctl restart konditoria
