name: Deploy to EC2 
on : 
  push : 
    branches : 
       - Elky_Schiff 
jobs : 
  deploy : 
    runs-on: ubuntu-latest 
    steps : 
       - name: Deploy to Server 
         uses: appleboy/ssh-action@v0.1.10 
         with :
          host: ${{ secrets.EC2_HOST_ELKY }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY_ELKY }}
          script: |
            # החליפי את my-project-folder בשם התיקייה האמיתי בשרת שלך
            cd /home/ubuntu/KonditoriaApp 
            git checkout Elky_Schiff
            git pull origin Elky_Schiff
            cd ./react
            npm install
            npm run build
            sudo cp -r dist/* /var/www/html/
             sudo systemctl restart Konditoria
