name: Deploy to EC2
on:
  push:
    branches:
      - SariLey

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # צעד שמפרק רק את ה-IP וה-User מה-Secret המשותף
      - name: Parse Secrets
        id: vars
        run: |
          echo "ip=$(echo '${{ secrets.SARILEVY_CONFIG }}' | jq -r '.ip')" >> $GITHUB_OUTPUT
          echo "user=$(echo '${{ secrets.SARILEVY_CONFIG }}' | jq -r '.user')" >> $GITHUB_OUTPUT

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          # כאן אנחנו שואבים מה-JSON שפירקנו בצעד הקודם
          host: ${{ steps.vars.outputs.ip }}
          username: ${{ steps.vars.outputs.user }}
          
          # כאן אנחנו משתמשים ב-Secret הרגיל כמו המורה
          key: ${{ secrets.SSH_PRIVATE_KEY_SARILEVY }}
          
          script: |
            # עדכון הקוד מהגיט בשרת
            cd /home/ubuntu/KonditoriaApp
            git checkout SariLey
            git pull origin SariLey
            
            # בנייה והעתקה של הקליינט
            cd ./react
            npm install
            npm run build
            sudo cp -r dist/* /var/www/html/
            
            # אתחול הסרבר
            sudo systemctl restart konditoria
