name: Deploy Osnat Project to EC2

on:
  push:
    branches:
      - osnat_moshko

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Connect and deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_OSNAT }}
          username: ${{ secrets.EC2_USER_OSNAT }}
          key: ${{ secrets.EC2_SSH_KEY_OSNAT }}
          script: |
           
            cd ~/KonditoriaApp
            
          
            git pull origin osnat_moshko
            
            
            cd react
            npm install
            npm run build
            sudo cp -r dist/* /var/www/html/
            
            
            cd ../node.js
            npm install
            
            # הפעלה מחדש של השירות (Service)
            sudo systemctl restart bakery.service
