name: Deploy to EC2
on:
  push:
    branches:
      - sarivolpo
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP_SARIVOLPO }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY_SARIVOLPO }}
          script: |
            echo "Starting deployment..."
            cd /home/ubuntu/KonditoriaApp || { echo "Failed to change directory"; exit 1; }
            echo "Checking out branch sarivolpo..."
            git checkout sarivolpo || { echo "Failed to checkout branch"; exit 1; }
            echo "Pulling latest changes from origin..."
            git pull origin sarivolpo || { echo "Failed to pull changes"; exit 1; }
            echo "Navigating to react directory..."
            cd ./react || { echo "Failed to change directory to react"; exit 1; }
            echo "Installing npm packages..."
            npm install || { echo "npm install failed"; exit 1; }
            echo "Building the client..."
            npm run build || { echo "npm run build failed"; exit 1; }
            echo "Copying files to /var/www/html/"
            sudo cp -r dist/* /var/www/html/ || { echo "Failed to copy files"; exit 1; }
            echo "Restarting server..."
            sudo systemctl restart konditoria || { echo "Failed to restart server"; exit 1; }
            echo "Deployment completed successfully."
