name: Deploy to EC2

on:
  push:
    branches:
      - esti_carmel

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_ESTI_CARMEL }}
          username: ${{ secrets.EC2_USER_ESTI_CARMEL }}
          key: ${{ secrets.EC2_SSH_KEY_ESTI_CARMEL }}
          script: |
            cd ~/KonditoriaApp
            git pull origin esti-carmel

            cd react
            npm install
            npm run build
            sudo cp -r dist/* /var/www/html/

            cd ../node.js
            npm install

            sudo systemctl restart bakery.service
