name: Deploy to EC2
on:
  push:
    branches:
      - yehudit_shraga

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Connect and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_YEHUDIT_SHRAGA }}
          username: ${{ secrets.EC2_USER_YEHUDIT_SHRAGA }}
          key: ${{ secrets.EC2_SSH_KEY_YEHUDIT_SHRAGA }}
          script: |
            cd ~/KonditoriaApp
            git pull origin yehudit_shraga
            cd react
            npm install
            npm run build
            sudo cp -r dist/* /var/www/html/
            cd ../node.js
            npm install
            sudo systemctl restart bakery.service
